name: Run Lint

on: [push, pull_request]

jobs:
  build:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.8.0
        uses: actions/setup-node@v1
        with:
          node-version: 14.8.0

      - name: Install Deps
        run: npm install

      - name: Lint
        run: npm run lint
