name: Run tests
on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: pnpm/action-setup@0609f0983b7a228f052f81ef4c3d6510cae254ad
          with:
            version: 8.7.0
        - uses: actions/setup-node@v3
          with:
            node-version: '18'
            cache: 'pnpm'
        - run: pnpm install
        - run: pnpm test
